manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/wellitonscheer
  projects:
    - name: corne-lp-wireless
      remote: zmkfirmware
      revision: master
      import: app/west.yml
  self:
    path: config
