manifest:
  remotes:
    - name: corne-lp-wireless
      url-base: https://github.com/wellitonscheer
  projects:
    - name: zmk
      remote: corne-lp-wireless
      revision: master
      import: app/west.yml
  self:
    path: config
